// Package redis provides an IdempotencyRecordRepository backed by Redis.
// It uses Lua scripts for atomic begin/commit/abort operations, making it
// safe for distributed deployments.
package redis

import (
	"context"
	"errors"
	"fmt"
	"time"

	goredis "github.com/redis/go-redis/v9"

	"github.com/sevenjl/go-zero-idempotency-plugin-development/domain/model"
	"github.com/sevenjl/go-zero-idempotency-plugin-development/domain/valueobject"
)

// ErrBreakerOpen is returned when the circuit breaker is open and the
// storage failure mode is fail_open. Callers can use errors.Is to detect
// this condition and choose to pass through to the business handler.
var ErrBreakerOpen = errors.New("redis: circuit breaker open")

// redisClient is the subset of go-zero's *redis.Redis that this
// repository needs. It matches the methods on redis.RedisNode.
type redisClient interface {
	GetCtx(ctx context.Context, key string) (string, error)
	SetCtxEx(ctx context.Context, key, value string, seconds int) error
	DelCtx(ctx context.Context, keys ...string) (int, error)
	ScriptRunCtx(ctx context.Context, script *goredis.Script, keys []string, args ...any) (any, error)
}

// IdempotencyRecordRepository implements domain/repository.IdempotencyRecordRepository
// with Redis as the backing store.
type IdempotencyRecordRepository struct {
	client    redisClient
	keyPrefix string
	hashTag   string          // Redis Cluster hash tag; empty means no tag
	breaker   *circuitBreaker // nil when circuit breaker is disabled
}

// RepositoryOption configures the Redis repository.
type RepositoryOption func(*IdempotencyRecordRepository)

// WithKeyPrefix sets the Redis key prefix. Defaults to "idem".
func WithKeyPrefix(prefix string) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		r.keyPrefix = prefix
	}
}

// WithHashTag enables Redis Cluster compatibility by wrapping the key prefix
// in a hash tag. All keys generated by this repository will share the same
// slot, which is required for Lua scripts to execute atomically.
//
// Example:
//
//	repo := NewIdempotencyRecordRepository(rds,
//	    WithKeyPrefix("idem"),
//	    WithHashTag("order-api"),
//	)
//	// Keys will look like: {order-api}:idem:key-001
//
// Without a hash tag the keys use the format "prefix:key" which works for
// standalone Redis but may fail in Cluster mode.
func WithHashTag(tag string) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		r.hashTag = tag
	}
}

// WithStorageFailureMode sets the behaviour when Redis is unavailable.
//   - "fail_closed" (default): reject requests and propagate the Redis error.
//   - "fail_open": pass through to the business handler even if idempotency
//     cannot be guaranteed.
//
// fail_open is only meaningful when a circuit breaker is configured (see
// WithBreakerMaxFailures).
func WithStorageFailureMode(mode string) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		if r.breaker == nil {
			r.breaker = newCircuitBreaker(storageFailureMode(mode), 5, 30*time.Second)
		} else {
			r.breaker.mode = storageFailureMode(mode)
		}
	}
}

// WithBreakerMaxFailures sets the number of consecutive Redis failures before
// the circuit breaker opens. Defaults to 5. Set to 0 to disable the breaker.
func WithBreakerMaxFailures(n int) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		if n <= 0 {
			r.breaker = nil
			return
		}
		if r.breaker == nil {
			r.breaker = newCircuitBreaker(storageFailClosed, n, 30*time.Second)
		} else {
			r.breaker.maxFailures = n
		}
	}
}

// WithBreakerCooldown sets the cooldown period after which the circuit breaker
// transitions from open to half-open. Defaults to 30s.
func WithBreakerCooldown(d time.Duration) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		if r.breaker == nil {
			r.breaker = newCircuitBreaker(storageFailClosed, 5, d)
		} else {
			r.breaker.cooldown = d
		}
	}
}

// NewIdempotencyRecordRepository creates a Redis-backed repository.
// The rds parameter must be a *redis.Redis from go-zero's
// github.com/zeromicro/go-zero/core/stores/redis package.
func NewIdempotencyRecordRepository(rds redisClient, opts ...RepositoryOption) *IdempotencyRecordRepository {
	repo := &IdempotencyRecordRepository{
		client:    rds,
		keyPrefix: "idem",
	}
	for _, opt := range opts {
		opt(repo)
	}
	return repo
}

// breakerAllow checks whether the circuit breaker permits this request.
// When the breaker is nil (disabled) or closed/half-open it returns nil,
// allowing the caller to proceed. When open, it returns ErrBreakerOpen.
func (r *IdempotencyRecordRepository) breakerAllow() error {
	if r.breaker == nil {
		return nil
	}
	if !r.breaker.allow() {
		return ErrBreakerOpen
	}
	return nil
}

// breakerRecord reports the outcome of a Redis operation to the breaker.
func (r *IdempotencyRecordRepository) breakerRecord(err error) {
	if r.breaker == nil {
		return
	}
	if err != nil {
		r.breaker.recordFailure()
	} else {
		r.breaker.recordSuccess()
	}
}

// redisKey builds the full Redis key. When hashTag is set the key is
// compatible with Redis Cluster — all keys with the same tag hash to
// the same slot, allowing Lua scripts to run atomically.
//
// Formats:
//
//	without hash tag:  idem:key-001
//	with hash tag:     {order-api}:idem:key-001
func (r *IdempotencyRecordRepository) redisKey(key string) string {
	if r.hashTag != "" {
		return fmt.Sprintf("{%s}:%s:%s", r.hashTag, r.keyPrefix, key)
	}
	return fmt.Sprintf("%s:%s", r.keyPrefix, key)
}

// TryBegin implements repository.IdempotencyRecordRepository.
func (r *IdempotencyRecordRepository) TryBegin(ctx context.Context, record *model.IdempotencyRecord) (model.BeginDecision, error) {
	if err := r.breakerAllow(); err != nil {
		return model.BeginDecision{}, err
	}

	recordJSON, err := marshalRecord(record)
	if err != nil {
		r.breakerRecord(err)
		return model.BeginDecision{}, fmt.Errorf("redis: marshal record: %w", err)
	}

	storeKey := r.redisKey(record.Key().String())
	ttl := int(record.ExpiresAt().Sub(record.CreatedAt()).Seconds())
	if ttl <= 0 {
		ttl = 30
	}

	result, err := r.client.ScriptRunCtx(ctx, beginScript, []string{storeKey},
		string(recordJSON),
		ttl,
		record.Fingerprint().String(),
	)
	r.breakerRecord(err)
	if err != nil {
		return model.BeginDecision{}, fmt.Errorf("redis: begin script: %w", err)
	}

	payload := []byte(luaPayload(result))
	switch luaResult(result) {
	case luaAcquired:
		existing, _ := unmarshalRecord(payload)
		return model.Acquired(existing), nil
	case luaReplay:
		existing, _ := unmarshalRecord(payload)
		return model.Replay(existing), nil
	case luaConflict:
		existing, _ := unmarshalRecord(payload)
		return model.Conflict(existing), nil
	case luaInProgress:
		existing, _ := unmarshalRecord(payload)
		return model.InProgress(existing), nil
	case luaFailed:
		existing, _ := unmarshalRecord(payload)
		return model.Failed(existing), nil
	default:
		return model.BeginDecision{}, fmt.Errorf("redis: unexpected begin result: %s", luaResult(result))
	}
}

// Commit implements repository.IdempotencyRecordRepository.
func (r *IdempotencyRecordRepository) Commit(ctx context.Context, record *model.IdempotencyRecord) error {
	if err := r.breakerAllow(); err != nil {
		return err
	}

	recordJSON, err := marshalRecord(record)
	if err != nil {
		r.breakerRecord(err)
		return fmt.Errorf("redis: marshal record: %w", err)
	}

	storeKey := r.redisKey(record.Key().String())
	ttl := int(time.Until(record.ExpiresAt()).Seconds())
	if ttl <= 0 {
		ttl = 86400
	}

	result, err := r.client.ScriptRunCtx(ctx, commitScript, []string{storeKey},
		record.Owner().String(),
		record.Fingerprint().String(),
		string(recordJSON),
		ttl,
	)
	r.breakerRecord(err)
	if err != nil {
		return fmt.Errorf("redis: commit script: %w", err)
	}

	switch luaResult(result) {
	case luaCommitted:
		return nil
	case luaMissing:
		return model.ErrInvalidState
	case luaOwnerMismatch:
		return model.ErrOwnerMismatch
	case luaConflict:
		return model.ErrFingerprintConflict
	case luaInvalidState:
		return model.ErrInvalidState
	default:
		return fmt.Errorf("redis: unexpected commit result: %s", luaResult(result))
	}
}

// Abort implements repository.IdempotencyRecordRepository.
func (r *IdempotencyRecordRepository) Abort(ctx context.Context, key valueobject.IdempotencyKey, owner valueobject.Owner, mode model.FailureMode) error {
	if err := r.breakerAllow(); err != nil {
		return err
	}

	storeKey := r.redisKey(key.String())

	var recordJSON string
	var failedTTL int

	if mode == model.FailureModeCache {
		// For cache mode the application layer already handles it via
		// record.MarkFailed + repo.Commit.
	}

	result, err := r.client.ScriptRunCtx(ctx, abortScript, []string{storeKey},
		owner.String(),
		string(mode),
		recordJSON,
		failedTTL,
	)
	r.breakerRecord(err)
	if err != nil {
		return fmt.Errorf("redis: abort script: %w", err)
	}

	switch luaResult(result) {
	case luaDeleted, luaCached, "ok":
		return nil
	case luaOwnerMismatch:
		return model.ErrOwnerMismatch
	case luaInvalidState:
		return model.ErrInvalidState
	default:
		return fmt.Errorf("redis: unexpected abort result: %s", luaResult(result))
	}
}

// Find implements repository.IdempotencyRecordRepository.
func (r *IdempotencyRecordRepository) Find(ctx context.Context, key valueobject.IdempotencyKey) (*model.IdempotencyRecord, error) {
	if err := r.breakerAllow(); err != nil {
		return nil, err
	}

	storeKey := r.redisKey(key.String())
	data, err := r.client.GetCtx(ctx, storeKey)
	if err != nil {
		// goredis.Nil means the key simply does not exist — not a storage error.
		if err == goredis.Nil {
			r.breakerRecord(nil)
			return nil, nil
		}
		r.breakerRecord(err)
		return nil, fmt.Errorf("redis: find get: %w", err)
	}
	r.breakerRecord(nil)

	record, err := unmarshalRecord([]byte(data))
	if err != nil {
		return nil, fmt.Errorf("redis: unmarshal record: %w", err)
	}
	return record, nil
}

// Renew implements repository.IdempotencyRecordRepository.
func (r *IdempotencyRecordRepository) Renew(ctx context.Context, key valueobject.IdempotencyKey, owner valueobject.Owner, ttl time.Duration) error {
	if err := r.breakerAllow(); err != nil {
		return err
	}

	storeKey := r.redisKey(key.String())
	seconds := int(ttl.Seconds())
	if seconds <= 0 {
		seconds = 30
	}

	result, err := r.client.ScriptRunCtx(ctx, renewScript, []string{storeKey},
		owner.String(),
		seconds,
	)
	r.breakerRecord(err)
	if err != nil {
		return fmt.Errorf("redis: renew script: %w", err)
	}

	switch luaResult(result) {
	case luaRenewed, "ok":
		return nil
	case luaMissing:
		return nil
	case luaOwnerMismatch:
		return model.ErrOwnerMismatch
	default:
		return fmt.Errorf("redis: unexpected renew result: %s", luaResult(result))
	}
}
