// Package redis provides an IdempotencyRecordRepository backed by Redis.
// It uses Lua scripts for atomic begin/commit/abort operations, making it
// safe for distributed deployments.
package redis

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"time"

	goredis "github.com/redis/go-redis/v9"

	"github.com/sevenjl/go-zero-idempotency-plugin-development/domain/model"
	domainrepo "github.com/sevenjl/go-zero-idempotency-plugin-development/domain/repository"
	"github.com/sevenjl/go-zero-idempotency-plugin-development/domain/valueobject"
)

// ErrBreakerOpen is returned when the circuit breaker is open and the
// storage failure mode is fail_open. Callers can use errors.Is to detect
// this condition and choose to pass through to the business handler.
var ErrBreakerOpen = fmt.Errorf("redis: circuit breaker open: %w", domainrepo.ErrStoragePassThrough)

// redisClient is the subset of go-zero's *redis.Redis that this
// repository needs. It matches the methods on redis.RedisNode.
type redisClient interface {
	GetCtx(ctx context.Context, key string) (string, error)
	SetCtxEx(ctx context.Context, key, value string, seconds int) error
	DelCtx(ctx context.Context, keys ...string) (int, error)
	ScriptRunCtx(ctx context.Context, script *goredis.Script, keys []string, args ...any) (any, error)
}

// IdempotencyRecordRepository implements domain/repository.IdempotencyRecordRepository
// with Redis as the backing store.
type IdempotencyRecordRepository struct {
	client    redisClient
	keyPrefix string
	hashTag   string          // Redis Cluster hash tag; empty means no tag
	breaker   *circuitBreaker // nil when circuit breaker is disabled
	encryptor BodyEncryptor   // nil means no encryption (plain base64)
	notifier  *PubSubNotifier // nil means no pub/sub notifications

	// Pending breaker config — used to accumulate settings before construction.
	breakerMode     storageFailureMode
	breakerFailures int
	breakerCooldown time.Duration
	breakerModeSet  bool
	breakerDisabled bool
}

// RepositoryOption configures the Redis repository.
type RepositoryOption func(*IdempotencyRecordRepository)

// WithKeyPrefix sets the Redis key prefix. Defaults to "idem".
func WithKeyPrefix(prefix string) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		r.keyPrefix = prefix
	}
}

// WithHashTag enables Redis Cluster compatibility by wrapping the key prefix
// in a hash tag. All keys generated by this repository will share the same
// slot, which is required for Lua scripts to execute atomically.
//
// Example:
//
//	repo := NewIdempotencyRecordRepository(rds,
//	    WithKeyPrefix("idem"),
//	    WithHashTag("order-api"),
//	)
//	// Keys will look like: {order-api}:idem:key-001
//
// Without a hash tag the keys use the format "prefix:key" which works for
// standalone Redis but may fail in Cluster mode.
func WithHashTag(tag string) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		r.hashTag = tag
	}
}

// WithStorageFailureMode sets the behaviour when Redis is unavailable.
//   - "fail_closed" (default): reject requests and propagate the Redis error.
//   - "fail_open": pass through to the business handler even if idempotency
//     cannot be guaranteed.
//
// fail_open is only meaningful when a circuit breaker is configured (see
// WithBreakerMaxFailures).
func WithStorageFailureMode(mode string) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		r.breakerMode = storageFailureMode(mode)
		r.breakerModeSet = true
	}
}

// WithBreakerMaxFailures sets the number of consecutive Redis failures before
// the circuit breaker opens. Defaults to 5. Set to 0 to disable the breaker.
func WithBreakerMaxFailures(n int) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		if n <= 0 {
			r.breakerDisabled = true
			return
		}
		r.breakerFailures = n
	}
}

// WithBreakerCooldown sets the cooldown period after which the circuit breaker
// transitions from open to half-open. Defaults to 30s.
func WithBreakerCooldown(d time.Duration) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		if d > 0 {
			r.breakerCooldown = d
		}
	}
}

// WithBodyEncryptor enables AES-GCM encryption for response bodies stored
// in Redis. When set, bodies are encrypted before base64 encoding during
// write and decrypted after base64 decoding during read.
//
// Without this option, bodies are stored as plain base64 — suitable for
// non-sensitive data but insufficient for PII or financial information.
func WithBodyEncryptor(encryptor BodyEncryptor) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		r.encryptor = encryptor
	}
}

// WithPubSubNotifier enables Redis Pub/Sub notifications for state transitions.
// When set, the repository publishes events on Complete and Abort, allowing
// waiters to be notified in real-time instead of polling.
//
// The application-layer IdempotencyService automatically detects the Notifier
// port and uses it when available.
func WithPubSubNotifier(notifier *PubSubNotifier) RepositoryOption {
	return func(r *IdempotencyRecordRepository) {
		r.notifier = notifier
	}
}

// NewIdempotencyRecordRepository creates a Redis-backed repository.
// The rds parameter must be a *redis.Redis from go-zero's
// github.com/zeromicro/go-zero/core/stores/redis package.
func NewIdempotencyRecordRepository(rds redisClient, opts ...RepositoryOption) *IdempotencyRecordRepository {
	repo := &IdempotencyRecordRepository{
		client:    rds,
		keyPrefix: "idem",
	}
	for _, opt := range opts {
		opt(repo)
	}
	// Build circuit breaker from accumulated config after all options applied.
	// This ensures option ordering does not silently disable the breaker.
	if !repo.breakerDisabled {
		failures := repo.breakerFailures
		if failures <= 0 {
			failures = 5
		}
		cooldown := repo.breakerCooldown
		if cooldown <= 0 {
			cooldown = 30 * time.Second
		}
		mode := repo.breakerMode
		if !repo.breakerModeSet {
			mode = storageFailClosed
		}
		repo.breaker = newCircuitBreaker(mode, failures, cooldown)
	}
	return repo
}

// breakerAllow checks whether the circuit breaker permits this request.
// When the breaker is nil (disabled) or closed/half-open it returns nil,
// allowing the caller to proceed. When open, it returns ErrBreakerOpen.
func (r *IdempotencyRecordRepository) breakerAllow() error {
	if r.breaker == nil {
		return nil
	}
	if !r.breaker.allow() {
		return ErrBreakerOpen
	}
	return nil
}

// breakerRecord reports the outcome of a Redis operation to the breaker.
func (r *IdempotencyRecordRepository) breakerRecord(err error) {
	if r.breaker == nil {
		return
	}
	if err != nil {
		r.breaker.recordFailure()
	} else {
		r.breaker.recordSuccess()
	}
}

// redisKey builds the full Redis key. When hashTag is set the key is
// compatible with Redis Cluster — all keys with the same tag hash to
// the same slot, allowing Lua scripts to run atomically.
//
// Formats:
//
//	without hash tag:  idem:key-001
//	with hash tag:     {order-api}:idem:key-001
func (r *IdempotencyRecordRepository) redisKey(key string) string {
	if r.hashTag != "" {
		return fmt.Sprintf("{%s}:%s:%s", r.hashTag, r.keyPrefix, key)
	}
	return fmt.Sprintf("%s:%s", r.keyPrefix, key)
}

func (r *IdempotencyRecordRepository) redisScopedKey(key string, scope valueobject.Scope) string {
	return r.redisKey(scopedStorageKey(key, scope))
}

// TryBegin implements repository.IdempotencyRecordRepository.
func (r *IdempotencyRecordRepository) TryBegin(ctx context.Context, record *model.IdempotencyRecord) (model.BeginDecision, error) {
	if err := r.breakerAllow(); err != nil {
		return model.BeginDecision{}, err
	}

	recordJSON, err := marshalRecord(record, r.encryptor)
	if err != nil {
		r.breakerRecord(err)
		return model.BeginDecision{}, fmt.Errorf("redis: marshal record: %w", err)
	}

	storeKey := r.redisScopedKey(record.Key().String(), record.Scope())
	ttl := int(record.ExpiresAt().Sub(record.CreatedAt()).Seconds())
	if ttl <= 0 {
		ttl = 30
	}

	result, err := r.client.ScriptRunCtx(ctx, beginScript, []string{storeKey},
		string(recordJSON),
		ttl,
		record.Fingerprint().String(),
	)
	r.breakerRecord(err)
	if err != nil {
		return model.BeginDecision{}, fmt.Errorf("redis: begin script: %w", err)
	}

	payload := []byte(luaPayload(result))
	switch luaResult(result) {
	case luaAcquired:
		existing, _ := unmarshalRecord(payload, r.encryptor)
		return model.Acquired(existing), nil
	case luaReplay:
		existing, err := unmarshalRecord(payload, r.encryptor)
		if err != nil {
			return model.BeginDecision{}, fmt.Errorf("redis: unmarshal replay record: %w", err)
		}
		return model.Replay(existing), nil
	case luaConflict:
		existing, err := unmarshalRecord(payload, r.encryptor)
		if err != nil {
			return model.BeginDecision{}, fmt.Errorf("redis: unmarshal conflict record: %w", err)
		}
		return model.Conflict(existing), nil
	case luaInProgress:
		existing, err := unmarshalRecord(payload, r.encryptor)
		if err != nil {
			return model.BeginDecision{}, fmt.Errorf("redis: unmarshal in-progress record: %w", err)
		}
		return model.InProgress(existing), nil
	case luaFailed:
		existing, err := unmarshalRecord(payload, r.encryptor)
		if err != nil {
			return model.BeginDecision{}, fmt.Errorf("redis: unmarshal failed record: %w", err)
		}
		return model.Failed(existing), nil
	default:
		return model.BeginDecision{}, fmt.Errorf("redis: unexpected begin result: %s", luaResult(result))
	}
}

// Commit implements repository.IdempotencyRecordRepository.
func (r *IdempotencyRecordRepository) Commit(ctx context.Context, record *model.IdempotencyRecord) error {
	if err := r.breakerAllow(); err != nil {
		return err
	}

	recordJSON, err := marshalRecord(record, r.encryptor)
	if err != nil {
		r.breakerRecord(err)
		return fmt.Errorf("redis: marshal record: %w", err)
	}

	storeKey := r.redisScopedKey(record.Key().String(), record.Scope())
	ttl := int(time.Until(record.ExpiresAt()).Seconds())
	if ttl <= 0 {
		ttl = 86400
	}

	result, err := r.client.ScriptRunCtx(ctx, commitScript, []string{storeKey},
		record.Owner().String(),
		record.Fingerprint().String(),
		string(recordJSON),
		ttl,
	)
	r.breakerRecord(err)
	if err != nil {
		return fmt.Errorf("redis: commit script: %w", err)
	}

	switch luaResult(result) {
	case luaCommitted:
		return nil
	case luaMissing:
		return model.ErrInvalidState
	case luaOwnerMismatch:
		return model.ErrOwnerMismatch
	case luaConflict:
		return model.ErrFingerprintConflict
	case luaInvalidState:
		return model.ErrInvalidState
	default:
		return fmt.Errorf("redis: unexpected commit result: %s", luaResult(result))
	}
}

// Abort implements repository.IdempotencyRecordRepository.
func (r *IdempotencyRecordRepository) Abort(ctx context.Context, key valueobject.IdempotencyKey, owner valueobject.Owner, mode model.FailureMode) error {
	return r.AbortScoped(ctx, key, valueobject.Scope{}, owner, mode)
}

func (r *IdempotencyRecordRepository) AbortScoped(ctx context.Context, key valueobject.IdempotencyKey, scope valueobject.Scope, owner valueobject.Owner, mode model.FailureMode) error {
	if err := r.breakerAllow(); err != nil {
		return err
	}

	storeKey := r.redisScopedKey(key.String(), scope)

	var recordJSON string
	var failedTTL int

	if mode == model.FailureModeCache {
		// For cache mode the application layer already handles it via
		// record.MarkFailed + repo.Commit.
	}

	result, err := r.client.ScriptRunCtx(ctx, abortScript, []string{storeKey},
		owner.String(),
		string(mode),
		recordJSON,
		failedTTL,
	)
	r.breakerRecord(err)
	if err != nil {
		return fmt.Errorf("redis: abort script: %w", err)
	}

	switch luaResult(result) {
	case luaDeleted, luaCached, "ok":
		return nil
	case luaOwnerMismatch:
		return model.ErrOwnerMismatch
	case luaInvalidState:
		return model.ErrInvalidState
	default:
		return fmt.Errorf("redis: unexpected abort result: %s", luaResult(result))
	}
}

// Find implements repository.IdempotencyRecordRepository.
func (r *IdempotencyRecordRepository) Find(ctx context.Context, key valueobject.IdempotencyKey) (*model.IdempotencyRecord, error) {
	return r.FindScoped(ctx, key, valueobject.Scope{})
}

func (r *IdempotencyRecordRepository) FindScoped(ctx context.Context, key valueobject.IdempotencyKey, scope valueobject.Scope) (*model.IdempotencyRecord, error) {
	if err := r.breakerAllow(); err != nil {
		return nil, err
	}

	storeKey := r.redisScopedKey(key.String(), scope)
	data, err := r.client.GetCtx(ctx, storeKey)
	if err != nil {
		// goredis.Nil means the key simply does not exist — not a storage error.
		if errors.Is(err, goredis.Nil) {
			r.breakerRecord(nil)
			return nil, nil
		}
		r.breakerRecord(err)
		return nil, fmt.Errorf("redis: find get: %w", err)
	}
	r.breakerRecord(nil)

	record, err := unmarshalRecord([]byte(data), r.encryptor)
	if err != nil {
		return nil, fmt.Errorf("redis: unmarshal record: %w", err)
	}
	return record, nil
}

// Renew implements repository.IdempotencyRecordRepository.
func (r *IdempotencyRecordRepository) Renew(ctx context.Context, key valueobject.IdempotencyKey, owner valueobject.Owner, ttl time.Duration) error {
	return r.RenewScoped(ctx, key, valueobject.Scope{}, owner, ttl)
}

func (r *IdempotencyRecordRepository) RenewScoped(ctx context.Context, key valueobject.IdempotencyKey, scope valueobject.Scope, owner valueobject.Owner, ttl time.Duration) error {
	if err := r.breakerAllow(); err != nil {
		return err
	}

	storeKey := r.redisScopedKey(key.String(), scope)
	seconds := int(ttl.Seconds())
	if seconds <= 0 {
		seconds = 30
	}

	result, err := r.client.ScriptRunCtx(ctx, renewScript, []string{storeKey},
		owner.String(),
		seconds,
	)
	r.breakerRecord(err)
	if err != nil {
		return fmt.Errorf("redis: renew script: %w", err)
	}

	switch luaResult(result) {
	case luaRenewed, "ok":
		return nil
	case luaMissing:
		return nil
	case luaOwnerMismatch:
		return model.ErrOwnerMismatch
	default:
		return fmt.Errorf("redis: unexpected renew result: %s", luaResult(result))
	}
}

func scopedStorageKey(key string, scope valueobject.Scope) string {
	if scope.IsZero() {
		return key
	}
	sum := sha256.Sum256([]byte(scope.Service() + "\x00" + scope.Tenant() + "\x00" + scope.User()))
	return key + ":scope:" + hex.EncodeToString(sum[:8])
}
