{{- if .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idempotency-example.fullname" . }}-redis
  labels:
    {{- include "idempotency-example.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
